services:

  backend:
    build: ./backend
    container_name: sentinel_backend
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      CAMERA_SERVICE_URL: http://host.docker.internal:9000
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: sentinel_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: sentinel_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dashboard_demo
      MYSQL_USER: admin
      MYSQL_PASSWORD: wSevGynJi29
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -proot --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

volumes:
  mysql_data: